deb build fix

diff --git a/install/workerd b/install/workerd
--- a/install/workerd
+++ b/install/workerd
@@ -1,86 +1,67 @@
-#!/bin/sh
-
+#! /bin/sh
 ### BEGIN INIT INFO
-# Provides:	  workerd
-# Required-Start:    $local_fs $remote_fs $network $syslog $named
-# Required-Stop:     $local_fs $remote_fs $network $syslog $named
-# Default-Start:     2 3 4 5
-# Default-Stop:      0 1 6
-# Short-Description: starts the workerd web server
-# Description:       starts workerd using start-stop-daemon
+# Provides:	        keywords-indexcreator
+# Required-Start:	$syslog $remote_fs
+# Required-Stop:	$syslog $remote_fs
+# Should-Start:		$local_fs
+# Should-Stop:		$local_fs
+# Default-Start:	2 3 4 5
+# Default-Stop:     0 1 6
+# Short-Description:    keywords-indexcreator
+# Description:      keywords-indexcreator for RG (getmyad-worker)
 ### END INIT INFO
+
 
 PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
 DAEMON=/usr/sbin/workerd
-CONFIG="/etc/workerd/config.xml"
-DAEMON_OPTS="-c $CONFIG"
+DAEMON_ARGS="-c /etc/workerd/config-workerd.xml"
 NAME=workerd
-DESC="worker daemon"
+DESC=workerd
+RUNDIR=/run/workerd
+PIDFILE=$RUNDIR/pid
+SOKET=$RUNDIR/sock
+USER=www-data
+GROUP=www-data
 
-. /lib/lsb/init-functions
-
-# Include workerd defaults if available
-if [ ! -f $CONFIG ]; then
-	echo "no config file"
-	exit 1
-fi
-
-test -x $DAEMON || exit 0
-
-PID=`$DAEMON -p -c $CONFIG`
-
-start() {
-		start-stop-daemon --start --quiet --pidfile $PID \
-			--retry 5 --exec $DAEMON --oknodo -- $DAEMON_OPTS
-}
-
-stop() {
-		start-stop-daemon --stop --quiet --pidfile $PID \
-			--retry 5 --oknodo --exec $DAEMON
-}
+set -e
 
 case "$1" in
-	start)
-		log_daemon_msg "Starting $DESC" "$NAME"
-		start
-		log_end_msg $?
-		;;
+  start)
+	echo -n "Starting $DESC: "
+    mkdir -p $RUNDIR
+    chown -R $USER:$GROUP $RUNDIR
+	touch $PIDFILE
+	chown $USER:$GROUP $PIDFILE
+    if [ -f $SOKET ]
+    then
+        rm $SOKET
+    fi
+	if start-stop-daemon --start --quiet --umask 007 --pidfile $PIDFILE --chuid $USER:$GROUP --exec $DAEMON -- $DAEMON_ARGS
+	then
+		echo "$NAME."
+	else
+		echo "failed"
+	fi
+	;;
+  stop)
+	echo -n "Stopping $DESC: "
+	if start-stop-daemon --stop --retry 10 --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON
+	then
+		echo "$NAME."
+	else
+		echo "failed"
+	fi
+	rm -f $PIDFILE
+	;;
 
-	stop)
-		stop
-		log_daemon_msg "Stopping $DESC" "$NAME"
-		log_end_msg $?
-		;;
-
-	restart|force-reload)
-		log_daemon_msg "Restarting $DESC" "$NAME"
-		stop
-		sleep 1
-		start
-		log_end_msg $?
-		;;
-
-	reload)
-		log_daemon_msg "Reloading $DESC configuration" "$NAME"
-		start-stop-daemon --stop --signal HUP --quiet --pidfile $PID \
-			--oknodo --exec $DAEMON
-		log_end_msg $?
-		;;
-
-	configtest|testconfig)
-		log_daemon_msg "Testing $DESC configuration"
-		test_workerd_config
-		log_end_msg $?
-		;;
-
-	status)
-		status_of_proc -p $PID "$DAEMON"
-		;;
-
-	*)
-		echo "Usage: $NAME {start|stop|restart|reload|force-reload|status|configtest}" >&2
-		exit 1
-		;;
+  restart|force-reload)
+	${0} stop
+	${0} start
+	;;
+  *)
+	echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload}" >&2
+	exit 1
+	;;
 esac
 
 exit 0
